name: Python Application

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        instance: [1, 2, 3]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run the application for 3 minutes
      run: |
        python3 -u src/main.py &
        PID=$!
        sleep 180
        kill $PID

    - name: Combine output.txt files
      if: ${{ matrix.instance == 3 }}
      run: |
        cat output.txt >> warp.txt
        git add warp.txt

    - name: Commit and push warp.txt
      if: ${{ matrix.instance == 3 }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -m "Update warp.txt from GitHub Action"
        git push
